version: '2'

services:

  test-service:
    image: springio/test-service
    restart: unless-stopped
    depends_on:
      - eureka-server

  debug-service:
      image: springio/debug-service
      restart: unless-stopped
      depends_on:
        - eureka-server

  eureka-server:
    image: springio/eureka-server
    restart: unless-stoped
    ports:
      - "8761:8761"

  zuul-server:
    image: springio/zuul-server
    depends_on:
     - eureka-server
    ports:
      - "9090:9090"