spring:
  application:
    name: turbine-server

server:
  port: 5050

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

turbine:
  appConfig: test-service
  aggregator:
    clusterConfig: TEST-SERVICE
  InstanceMonitor:
    eventStream:
    skipLineLogic:
    enabled: false