server:
  port: 9000

spring:
  application:
    name: micro-service-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://micro-service-server:9000/eureka/

zuul:
  prefix: /api