server:
  port: 9000

spring:
  application:
    name: micro-service-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://micro-service-server:9000/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    test:
      path: /test/**
      serviceId: test-service
    debug:
      path: /debug/**
      serviceId: debug-service
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000

turbine:
  aggregator:
    clusterConfig: TEST-SERVICE
    appConfig: TEST-SERVICE

security:
  oauth2:
    resource:
      user-info-uri: http://sso-server:5050/auth/user

#security:
#  oauth2:
#    client:
#      accessTokenUri: http://micro-service-server:9000/api/sso-server/auth/token
#      userAuthorizationUri: http://micro-service-server:9000/api/sso-server/auth/authorize
#      clientId: clientapp2
#      clientSecret: 1234562
#    resource:
#      userInfoUri: http://micro-service-server:9000/api/sso-server/auth/user
#      preferTokenInfo: false