server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://micro-service-server:9000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: test-service

security:
  oauth2:
    resource:
      user-info-uri: http://micro-service-server:9000/api/sso-server/auth/user
