server:
  port: 5050

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://micro-service-server:9000/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

#security:
#  user:
#    name: user
#    password: user

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  application:
    name: sso-server

test:
  value: "test value"

oauthClients:
  clients:
    -
      name: clientapp
      secret: 123456
      accessTokenValiditySeconds: 7200
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
        - password
      scopes:
        - read
        - write
      resourcesId:
        - restservice
    -
      name: clientapp2
      secret: 1234562
      accessTokenValiditySeconds: 7200
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
        - password
      resourcesId:
        - restservice
      scopes:
        - read
        - write

logging:
  level:
    org.hibernate.SQL: debug
